### ISSUE TITLE
[benchmarking] undefined method for certain jruby versions

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-ruby#521] opened 2019-09-10 07:59 UTC
There are some recurrent errors when running the benchmarking stage for:

- docker.elastic.co/observability-ci/jruby:9.2-11-jdk
- docker.elastic.co/observability-ci/jruby:9.2-12-jdk
- docker.elastic.co/observability-ci/jruby:9.2-8-jdk
- jruby:9.2

```
bench/report.rb
 NoMethodError: undefined method `[]' for nil:NilClass
  <main> at bench/report.rb:48
```

Please refers to: 
- [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp/detail/master/53/pipeline/221)

**Comment by mikker** [comment] 2019-09-10 08:15
Yeah, I don't know. Couldn't reproduce it locally.

I suspect it comes from a lack of output (or wrongly formatted) from `bench/benchmark.rb`.

**Comment by v1v** [comment] 2019-09-10 15:40
I'll try to run the benchmark locally and see whether I can reproduce it, to double-check too what's going on

**Comment by v1v** [comment] 2019-09-17 12:39
I've just found the .error files contain more debug details, please see the below details for each failing version:


<details>
<summary>docker.elastic.co/observability-ci/jruby:9.2-8-jdk</summary>

```
NoMethodError: undefined method `new_column' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x7c51782d>
                columns at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:295
                    map at org/jruby/RubyArray.java:2577
                columns at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:282
                columns at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76
           columns_hash at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:82
           load_schema! at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:487
           load_schema! at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attributes.rb:247
           load_schema! at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attribute_decorators.rb:51
            load_schema at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:480
        mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:226
            load_schema at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:477
        attribute_types at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:362
     type_for_attribute at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:386
                   type at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/table_metadata.rb:33
                  build at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:51
       expand_from_hash at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:109
                   each at org/jruby/RubyHash.java:1419
               flat_map at org/jruby/RubyEnumerable.java:880
       expand_from_hash at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:68
        build_from_hash at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:21
                  build at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/where_clause_factory.rb:19
                 where! at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:645
                  where at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:638
                find_by at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:81
  find_or_initialize_by at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation.rb:227
  find_or_initialize_by at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/querying.rb:21
                    []= at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/internal_metadata.rb:24
                 define at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:58
                 define at /tmp/vendor/j9.2-8-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:46
                 <main> at /app/bench/app.rb:16
                require at org/jruby/RubyKernel.java:987
                 <main> at bench/benchmark.rb:13
```

[benchmark-jruby-9.2-8-jdk.error](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-529/3/artifact/benchmark-jruby-9.2-8-jdk.error/*view*/)
</details>

<details>
<summary>docker.elastic.co/observability-ci/jruby:9.2-11-jdk</summary>

```
NoMethodError: undefined method `new_column' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x6421e9e7>
                columns at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:295
                    map at org/jruby/RubyArray.java:2577
                columns at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:282
                columns at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76
           columns_hash at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:82
           load_schema! at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:487
           load_schema! at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attributes.rb:247
           load_schema! at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attribute_decorators.rb:51
            load_schema at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:480
        mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:226
            load_schema at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:477
        attribute_types at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:362
     type_for_attribute at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:386
                   type at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/table_metadata.rb:33
                  build at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:51
       expand_from_hash at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:109
                   each at org/jruby/RubyHash.java:1419
               flat_map at org/jruby/RubyEnumerable.java:880
       expand_from_hash at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:68
        build_from_hash at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:21
                  build at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/where_clause_factory.rb:19
                 where! at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:645
                  where at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:638
                find_by at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:81
  find_or_initialize_by at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation.rb:227
  find_or_initialize_by at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/querying.rb:21
                    []= at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/internal_metadata.rb:24
                 define at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:58
                 define at /tmp/vendor/j9.2-11-jdk/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:46
                 <main> at /app/bench/app.rb:16
                require at org/jruby/RubyKernel.java:987
                 <main> at bench/benchmark.rb:13

```

[benchmark-jruby-9.2-11-jdk.error](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-529/3/artifact/benchmark-jruby-9.2-11-jdk.error/*view*/)
</details>


<details>
<summary>docker.elastic.co/observability-ci/jruby:9.2-12-jdk</summary>

```
Bundler::GemNotFound: Could not find gem 'rack-test java' in any of the gem sources listed in your Gemfile.
  verify_gemfile_dependencies_are_found! at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/resolver.rb:287
                                    each at org/jruby/RubyArray.java:1792
  verify_gemfile_dependencies_are_found! at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/resolver.rb:255
                                   start at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/resolver.rb:49
                                 resolve at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/resolver.rb:22
                                 resolve at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/definition.rb:258
                                   specs at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/definition.rb:170
                               specs_for at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/definition.rb:237
                         requested_specs at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/definition.rb:226
                         requested_specs at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/runtime.rb:108
                                   setup at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/runtime.rb:20
                                   setup at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler.rb:107
                                  <main> at /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.0.2/lib/bundler/setup.rb:20
                                 require at org/jruby/RubyKernel.java:987
                                  (root) at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                                  <main> at bench/benchmark.rb:7
```

[benchmark-jruby-9.2-12-jdk.error](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-529/3/artifact/benchmark-jruby-9.2-12-jdk.error/*view*/)
</details>


<details>
<summary>jruby:9.2</summary>

```
NoMethodError: undefined method `new_column' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x1e469dfd>
                columns at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:295
                    map at org/jruby/RubyArray.java:2584
                columns at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-jdbc-adapter-50.0/lib/arjdbc/sqlite3/adapter.rb:282
                columns at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:76
           columns_hash at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/schema_cache.rb:82
           load_schema! at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:487
           load_schema! at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attributes.rb:247
           load_schema! at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/attribute_decorators.rb:51
            load_schema at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:480
        mon_synchronize at /opt/jruby/lib/ruby/stdlib/monitor.rb:226
            load_schema at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:477
        attribute_types at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:362
     type_for_attribute at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/model_schema.rb:386
                   type at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/table_metadata.rb:33
                  build at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:51
       expand_from_hash at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:109
                   each at org/jruby/RubyHash.java:1417
               flat_map at org/jruby/RubyEnumerable.java:905
       expand_from_hash at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:68
        build_from_hash at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/predicate_builder.rb:21
                  build at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/where_clause_factory.rb:19
                 where! at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:645
                  where at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/query_methods.rb:638
                find_by at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:81
  find_or_initialize_by at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/relation.rb:227
  find_or_initialize_by at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/querying.rb:21
                    []= at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/internal_metadata.rb:24
                 define at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:58
                 define at /tmp/vendor/j9.2/jruby/2.5.0/gems/activerecord-6.0.0/lib/active_record/schema.rb:46
                 <main> at /app/bench/app.rb:16
                require at org/jruby/RubyKernel.java:987
                 <main> at bench/benchmark.rb:13
```

[benchmark-jruby-9.2.error](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-529/3/artifact/benchmark-jruby-9.2.error/*view*/)
</details>

**Comment by mikker** [comment] 2019-09-18 08:34
Perhaps something related to this https://github.com/rails/rails/issues/10613#issuecomment-18757079

**Comment by mikker** [comment] 2019-11-20 11:36
@v1v Can we close this one?

**Comment by v1v** [comment] 2019-11-20 11:38
The workaround was to disable the benchmarking for `jruby:9.2`. Not sure, if that's sufficient, no strong opinions about it.

**Comment by mikker** [comment] 2019-11-20 12:32
Not optimal. I'll try if we can get it going again.

**Comment by v1v** [comment] 2020-01-20 12:27
This particular issue is related to https://github.com/elastic/apm-agent-ruby/pull/692:


When testing it locally I've got some warnings:

- `gem update --system` got `constant Gem::ConfigMap is deprecated` warning

```
+ gem update --system
Installing RubyGems 3.1.2
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:41: warning: constant Gem::ConfigMap is deprecated
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:42: warning: constant Gem::ConfigMap is deprecated
```


- `gem update --system` got `constant Gem::ConfigMap is deprecated` and `Gem::Specification#rubyforge_project= is deprecated` warnings
```
+ gem install bundler
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
1 gem installed
```

- `bundle install` got `constant Gem::ConfigMap is deprecated` and got unused dependency
```
+ bundle install
/opt/jruby/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
The dependency ruby-prof (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform ruby`.
The dependency stackprof (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform ruby`.

Resolving dependencies...................NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
```

**Closed** 2020-01-20 15:16 UTC
Labels: automation, bug, ci
