### ISSUE TITLE
Integration with log libraries to be able to tag log messages with trace/transaction

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-ruby#470] opened 2019-07-05 09:10 UTC

**Comment by mikker** [comment] 2019-07-05 09:12
Duplicate of https://github.com/elastic/apm-agent-ruby/issues/462 ?

**Comment by mikker** [comment] 2019-07-05 09:13
Updated the link in the meta issue 👍

**Closed by mikker** 2019-07-05 09:13 UTC
