### ISSUE TITLE
No Transactions and Errors Data

### ISSUE THREAD

**Issue by offspringus** [elastic/apm-agent-ruby#661] opened 2019-12-24 20:44 UTC
Hello,
Please help me deal with the problem.

I have installed apm-server (version 7.4.2 (amd64), libbeat 7.4.2)
Then install and configure elastic-apm gem
```
config/elastic_apm.yml:
service_name: 'XXXXXXX-beta'
server_url: 'http://xx.xx.xx.xx:8200'
```

After that I see service in kibana. I can see Metrics (CPU usage and System memory usage) but nothing else. Transactions and Errors are empty. Index apm-7.4.2-transaction-000001 is also empty.

There are error logs from apm-server:

2019-12-24T20:16:56.972Z	ERROR	[request]	middleware/log_middleware.go:74	internal error	{"request_id": "ce488a6f-691a-45ef-93c3-e3de22168cd0", "method": "POST", "URL": "/intake/v2/events", "content_length": -1, "remote_address": "172.31.15.122", "user-agent": "elastic-apm-ruby/3.3.0 http.rb/4.2.0 ruby/2.3.6", "response_code": 500, "error": "unexpected EOF"}
2019-12-24T20:17:50.032Z	ERROR	[request]	middleware/log_middleware.go:74	internal error	{"request_id": "af87e103-67c8-479c-8a31-29505f4947de", "method": "POST", "URL": "/intake/v2/events", "content_length": -1, "remote_address": "172.31.15.122", "user-agent": "elastic-apm-ruby/3.3.0 http.rb/4.2.0 ruby/2.3.6", "response_code": 500, "error": "read tcp 172.31.47.85:8200-172.31.15.122:47920: i/o timeout"}

What could be the problem?
![1](https://user-images.githubusercontent.com/8195696/71424839-e06ab800-269e-11ea-8d00-e4449e899d73.JPG)
![2](https://user-images.githubusercontent.com/8195696/71424840-e06ab800-269e-11ea-84a0-00cd5fcd28f7.JPG)
![3](https://user-images.githubusercontent.com/8195696/71424841-e1034e80-269e-11ea-84fb-8105d3937033.JPG)
![4](https://user-images.githubusercontent.com/8195696/71424842-e1034e80-269e-11ea-8d22-9c2b56521154.JPG)

**Comment by estolfo** [comment] 2020-01-02 20:57
Hi @offspringus 
Is this still an issue or have you resolved it already?
If you're still having trouble, can you let us know what your agent configured settings are, if not the defaults? I'm particularly interested in any timeout settings. 
Can you tell us some more about the setup of the app you're monitoring? Is it a high-traffic app?

There is [this issue](https://github.com/elastic/apm-server/issues/1585) showing a similar error. Does [this comment](https://github.com/elastic/apm-server/issues/1585#issuecomment-442093153) look like it'd help your situation?

**Comment by offspringus** [comment] 2020-01-02 22:11
Hi @estolfo and thanks for your message.
The problem is still here. 
I just add the agent to my Gemfile, then run bundle install.
I wrote in a post above how I configured the agent:
File config/elastic_apm.yml:
service_name: 'XXXXXXX-beta'
server_url: 'http://xx.xx.xx.xx:8200'
Also I tried adding:
api_request_time: '30s'
But it did not help. I do not have a load balancer. Server and agent communicate over local network.
It is not high-traffic, it is beta server for developers only.

**Comment by estolfo** [comment] 2020-01-02 22:26
Thanks for your response, @offspringus. Can you try configuring the agent with `log_level: 0` and let me know if there are any errors being logged?

**Comment by offspringus** [comment] 2020-01-02 22:32
@estolfo I added log_level: '0' to config file, restart nginx, but can't find where the logs :)

**Comment by estolfo** [comment] 2020-01-03 19:36
@offspringus Have you tried setting the `log_path` config option? You can use that to control where the agent logs go. [Here](https://www.elastic.co/guide/en/apm/agent/ruby/2.x/configuration.html#config-log-path) is the documentation.
I also just want to check- are you using Rails or another framework?

**Comment by offspringus** [comment] 2020-01-08 14:48
@estolfo yes, I added to the config log_path, but the file did not appear. 
I'm using:
$ ruby -v
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]

$ rails -v
Rails 4.1.8

**Comment by estolfo** [comment] 2020-05-06 10:24
Hi @offspringus is this still an issue?

**Comment by estolfo** [comment] 2020-05-12 09:14
I'm going to close this. Please reopen it if the issue is still relevant.

**Closed by estolfo** 2020-05-12 09:14 UTC

**Comment by Rfferrao87** [comment] 2020-10-22 16:27
If I may, I'd like to report the same issue happening with my django application configured as per the APM Agents wizard in Kibana 7.9.1.

**Comment by mikker** [comment] 2020-10-22 20:02
@Rfferrao87 Sorry to hear. This is the repo for the _Ruby_ agent, though. [elastic/apm-agent-python](https://github.com/elastic/apm-agent-python) has all the relevant Django and Python issues and information.
