### ISSUE TITLE
sql_summarizer - ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Cervenka** [elastic/apm-agent-ruby#595] opened 2019-10-30 14:41 UTC
Hello,
I am seeing following exception:

ArgumentError: invalid byte sequence in UTF-8
/gems/elastic-apm-3.1.0/lib/elastic_apm/sql_summarizer.rb:29

How can I mitigate this?

Thank you

**Comment by estolfo** [comment] 2019-10-30 15:02
Hi @Cervenka! Thanks for reporting this. It looks like we'll have to force the encoding on that line. We'll have a fix soon. Thanks!

**Comment by Cervenka** [comment] 2019-11-06 11:19
@estolfo, thank you for looking into this.

**Comment by estolfo** [comment] 2019-11-06 12:44
@Cervenka I just opened [a PR](https://github.com/elastic/apm-agent-ruby/pull/600) to resolve this. If you would have the chance to try it in your testing environment, that'd be great. Thanks!

**Comment by Cervenka** [comment] 2019-11-06 14:28
Hi, I did try your branch.

Other issues came up which may be cause by other commits? Rolling back to elastic-apm 3.1.0 instantly resolved this.

ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
ActionView::Template::Error: could not obtain a connection from the pool within 5.000 seconds
Mysql2::Error: Too many connections

**Comment by estolfo** [comment] 2019-11-06 14:31
hmm, thanks for letting me know. What is your connection pool size?

**Comment by Cervenka** [comment] 2019-11-06 14:33
mysql2 adapter with pool set to 5 per server

**Comment by estolfo** [comment] 2019-11-06 14:35
Can you checkout this commit and see if the problem goes away? 613d6fd59f8da6f9f56df9c0d6e95e766d28d9a6

**Comment by Cervenka** [comment] 2019-11-06 14:49
That commit does not cause the AR issues.

**Comment by estolfo** [comment] 2019-11-06 15:15
Thanks for your help in helping me find the culprit! I've just reverted two commits in the PR that I suspect are the issue. Would you mind trying the PR again? Thanks!

**Comment by Cervenka** [comment] 2019-11-06 15:31
That looks good! No errors so far.

remote: https://github.com/estolfo/apm-agent-ruby
revision: 7406f77a573ea28fb54a4309888882b38a2c17f1
ref: utf-8-sql

**Comment by estolfo** [comment] 2019-11-06 15:38
Ok, thanks for testing! I just opened [this issue](https://github.com/elastic/apm-agent-ruby/issues/601) to keep track of that ConnectionTimeoutError. Can you also tell me what version of Rails you are using?

Getting back to this issue itself, did you find that the `ArgumentError: invalid byte sequence in UTF-8` is gone as well?

**Comment by Cervenka** [comment] 2019-11-06 15:39
Rails 5.2.3
Yes, the original issue seems to be resolved.

**Comment by estolfo** [comment] 2019-11-06 15:40
Great, thank you for all your help!

**Comment by Cervenka** [comment] 2019-11-06 21:39
I caught another error

Encoding::UndefinedConversionError: "\xFD" from ASCII-8BIT to UTF-8

/bundler/gems/apm-agent-ruby-7406f77a573e/lib/elastic_apm/sql_summarizer.rb:30

From the airbrake notification:
```
...
 "messageParams": {
    "0": "�",
    "1": "ASCII-8BIT",
    "2": "UTF-8"
  },
...
```

**Comment by estolfo** [comment] 2019-11-07 08:31
That's unfortunate, thanks for letting me know.
Is there anything else you can tell me about the sql statement? Would you be able to give me an example statement, like the one that caused the last error?

**Comment by Cervenka** [comment] 2019-11-07 11:09
It turns out that a different library spits out some bad data in some cases. Here is part of the sql statement that is causing the issue. I'm rescuing the error for now. Thanks again!

`SELECT [REMOVED] AND `location`.`zone` IN ('GB', 'GB-�a��a��aN�aO�a8�a9�aP�aQ�aG�aH�aR�aS�a��a��aT�aU�') LIMIT 1`

**Comment by estolfo** [comment] 2019-11-07 11:11
Thanks for this!
I made another change an hour or two ago to the PR. Let me know if you have a chance to test it and if you see the error with the latest changes. Thanks!

**Comment by Cervenka** [comment] 2019-11-07 12:08
Everything looks good so far (25min)! Thanks!

**Comment by estolfo** [comment] 2019-11-07 12:45
Glad to hear it!

**Comment by estolfo** [comment] 2019-11-08 09:28
Hi @Cervenka can we consider this 'invalid byte sequence' issue fixed?
I have another issue open for the [ConnectionTimeoutError](https://github.com/elastic/apm-agent-ruby/issues/601). I might ping you with questions about how to reproduce that, if you don't mind.

**Comment by Cervenka** [comment] 2019-11-08 09:35
It seems that the forced encoding could cover more. Here more queries including gibberish. However your recent change does seem to cover 99% of the cases.

Perhaps it might be worthwhile to rescue the error on your end and replace the query with a notice that it could not be converted to UTF8.

```
{
  "error": "\"\\\"\\\\xFA\\\" from ASCII-8BIT to UTF-8\"",
  "mysql_query": "SELECT  [REMOVED] IN ('VG', 'VG-2wK\u0016iL\u0016iM\u0016iN\u0016i\fy|��v\f�}O\u0016iY\u0016iZ\u0016iP\u0016i�TQ\u0016i�T�TR\u0016') LIMIT 1"
}
```
```
{
  "error": "\"\\\"\\\\xB1\\\" from ASCII-8BIT to UTF-8\"",
  "mysql_query": "SELECT  [REMOVED] IN ('PK', 'PK-�x[wx��xH�\u0001��x��xJ�\u0001��xI�\u0001��x��x[wx��x��xM�\u0001S�\u0001T�') LIMIT 1"
}
```
```
{
  "error": "\"\\\"\\\\x82\\\" from ASCII-8BIT to UTF-8\"",
  "mysql_query": "SELECT  [REMOVED] IN ('MT', 'MT-�\u001f��\u001f�\u0001w��\u001f(�}�\u0001w��\u001f P���\u001f(�}E���\u0001w��\u001f��\u001f�\u0001w�\u0001w��') LIMIT 1"
}
```

**Comment by estolfo** [comment] 2019-11-08 10:04
So these errors are definitely coming from the APM agent? Can you send me the stacktrace from them?
The change that I made only converts a copy of the string so that the sql statement can be analyzed by the agent. The sql string itself is not mutated so it's possible that some other part of the application hits this error. What do you think?

I did make one other change to the PR, if you would like to start testing that.

**Comment by Cervenka** [comment] 2019-11-12 16:30
Hi,
it did originate from sql_summarizer.rb and not another location. I will fetch the gem from this repository again and will attempt to capture a stack trace.

Thanks again!

**Comment by estolfo** [comment] 2019-11-12 16:34
ok, we've merged the change into master, as well as the fix for [this](https://github.com/elastic/apm-agent-ruby/issues/601)
Let us know if you still encounter errors when testing master. Thanks again!

**Comment by Cervenka** [comment] 2019-11-13 10:47
Hi, this is the most recent backtrace:

```
{
  "backtrace": [
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/sql_summarizer.rb:28:in `encode'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/sql_summarizer.rb:28:in `summarize'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/normalizers/rails/active_record.rb:43:in `summarize'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/normalizers/rails/active_record.rb:27:in `normalize'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/normalizers.rb:55:in `normalize'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/subscriber.rb:36:in `start'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:100:in `start'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:44:in `block in start'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:44:in `each'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/fanout.rb:44:in `start'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:35:in `start'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:33:in `exec_query'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'",
    "(eval):2:in `select'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `block in select_all'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:127:in `block in cache_sql'",
    "/opt/nginx/embedded/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `select_all'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'",
    "(eval):2:in `select_all'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:77:in `select_one'",
    "(eval):2:in `select_one'",
    "(eval):5:in `block in select_one'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/active_record_slave-b9c80670a1a0/lib/active_record_slave/active_record_slave.rb:42:in `read_from_master'",
    "(eval):4:in `select_one'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:322:in `block in exists?'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/finder_methods.rb:322:in `exists?'",\
    ...
    [REMOVED]
    ...
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/serviceworker-rails-0.5.5/lib/serviceworker/middleware.rb:32:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/middleware.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-attack-5.4.2/lib/rack/attack.rb:182:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/remotipart-1.4.2/lib/remotipart/middleware.rb:32:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/airbrake-9.4.4/lib/airbrake/rack/middleware.rb:32:in `call!'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/airbrake-9.4.4/lib/airbrake/rack/middleware.rb:21:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/dragonfly-1.1.5/lib/dragonfly/cookie_monster.rb:9:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/bundler/gems/apm-agent-ruby-b68f1f12ae48/lib/elastic_apm/middleware.rb:20:in `call'",
    "/var/www/[removed]/shared/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'",
    "/opt/nginx/embedded/lib/ruby/gems/2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'",
    "/opt/nginx/embedded/lib/ruby/gems/2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'",
    "/opt/nginx/embedded/lib/ruby/gems/2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'",
    "/opt/nginx/embedded/lib/ruby/gems/2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'",
    "/opt/nginx/embedded/lib/ruby/gems/2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"
  ],
  "error": "\"\\\"\\\\xCB\\\" from ASCII-8BIT to UTF-8\"",
  "mysql_query": "SELECT  1 [REMOVED] IN ('AP', 'AP-Ps��,��,R�,S�,T�,U�,��,��,V�,W�,p�,q�,X�,Y�,c�,d�') LIMIT 1"
}
```

**Comment by estolfo** [comment] 2019-11-13 11:00
Thanks for that information, it made it clear that we also need to handle undefined characters. I've opened [this PR](https://github.com/elastic/apm-agent-ruby/pull/610) to do that. Let me know if you have a chance to test and thanks again for all your help!

**Comment by Cervenka** [comment] 2019-11-14 11:41
I'll give it a shot once it is in master. Thanks!

**Comment by estolfo** [comment] 2019-11-14 11:46
I just merged it into master = )
Thanks!

**Closed** 2019-11-14 11:45 UTC
Labels: [zube]: Inbox

**Comment by Cervenka** [comment] 2019-11-17 09:53
So far so good! Thanks again.
